import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Welcome to my portfolio + plus photo of myself or not</h1>

        <section id='About'>
          <h2>I am Feu Matthew Her + picture</h2>
          
          <p>

            I'm a full-stack developer who comes from the love of video games. My love for video games sparked an idea which brought me to coding.  So, I took 
            some class about computer science and coding. This simple exposure got me hooked into coding. I think getting my first simple function to render got me hooked. 
            It was so fastinating, fun, and challenging to get my code to work.
            Now, I believe that I am just passionate about technology. Technology is an tool that has no limits and is constantly evolving. Just being about to work with tech would be great. Being able to
            implement my thoughts, ideas, and skills into a job would be my dream job. I graduated from a bootcamp to become a software engineer.
            I believe that my bootcamp experience and exposure will help me become a software engineer that can
            thrive at any company.

          </p>

        </section>

        <section id='Project'>
          <h2>Project1 pic/thumbnail</h2>
          <p>project 1 summary + tech used</p>

          <h2>Project2 pic/thumbnail</h2>
          <p>project 2 summary +  tech used</p>

          <h2>Project3 pic/thumbnail</h2>
          <p>project 3 summary + tech/used</p>

        </section>

        <section id='Resume'>
          <h2>Resume</h2>
          <p>will be download resume or be link to resume</p>
        </section>

        <section id='Contact'>
          <h2>Contact information</h2>
          <p>phone number</p>
          <p>linkedin</p>
          <p>github</p>
        </section>

        <h1>Tech Stack</h1>
        <h1>js, html, css, git, react, mysql, mongoDB</h1>

        <footer>
          <h2>footer</h2>
          <h2>@etc</h2>
          <h2>©</h2>
        </footer>
        
      </main>
    </>
  )
}
